#user1

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXXXXXXXXXXX
      server: https://api.cloudopswithswapnil.in
      tls-server-name: api.internal.cloudopswithswapnil.in
    name: cloudopswithswapnil.in
contexts:
  - context:
      cluster: cloudopswithswapnil.in
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
      client-certificate: /root/user1.crt
      client-key: /root/user1.key

---
#user2

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXXXXXXXXXXXXXXXXX
      server: https://api.cloudopswithswapnil.in
      tls-server-name: api.internal.cloudopswithswapnil.in
    name: cloudopswithswapnil.in
contexts:
  - context:
      cluster: cloudopswithswapnil.in
      namespace: production
      user: user2
    name: user2-context
current-context: user2-context
kind: Config
users:
  - name: user2
    user:
      client-certificate: /root/user2.crt
      client-key: /root/user2.key

---
#swapnil (admin)

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      server: https://api.cloudopswithswapnil.in
      tls-server-name: api.internal.cloudopswithswapnil.in
    name: cloudopswithswapnil.in
contexts:
  - context:
      cluster: cloudopswithswapnil.in
      user: swapnil
    name: swapnil-context
current-context: swapnil-context
kind: Config
users:
  - name: swapnil
    user:
      client-certificate: /root/swapnil.crt
      client-key: /root/swapnil.key
